# ============================================================
# PART 2: STATE DESIGN
# ============================================================
# The CapstoneState TypedDict is the shared object ALL nodes
# read from and write to. Define this BEFORE any node function.
# ============================================================

from typing import TypedDict, List, Optional

class CapstoneState(TypedDict):
    question: str            # Current user question
    messages: List[dict]     # Full conversation history
    route: str               # Router decision: retrieve / tool / memory_only
    retrieved: str           # Retrieved context text from ChromaDB
    sources: List[str]       # Topic names of retrieved documents
    tool_result: str         # Result from tool_node (e.g. current date)
    answer: str              # Final answer generated by answer_node
    faithfulness: float      # Faithfulness score from eval_node (0.0 to 1.0)
    eval_retries: int        # How many times eval_node has retried
    customer_name: str       # Customer name extracted from conversation

print("✅ Part 2: CapstoneState defined.")


# ============================================================
# PART 3: NODE FUNCTIONS
# ============================================================
# 8 nodes, each does ONE job. Test each individually first.
# ============================================================

import os
from datetime import datetime
from langchain_groq import ChatGroq
from sentence_transformers import SentenceTransformer
import chromadb

# ── Configuration ────────────────────────────────────────────
GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "your_groq_api_key_here")
MODEL_NAME = "llama-3.3-70b-versatile"
FAITHFULNESS_THRESHOLD = 0.7
MAX_EVAL_RETRIES = 2
SLIDING_WINDOW = 6   # Keep last 6 messages to avoid token overflow

# ── Initialize shared resources ──────────────────────────────
print("\nInitializing LLM and embedder...")
llm = ChatGroq(api_key=GROQ_API_KEY, model_name=MODEL_NAME)
embedder = SentenceTransformer("all-MiniLM-L6-v2")

# Re-build ChromaDB (same as Part 1 — in production keep this shared)
client = chromadb.Client()
try:
    client.delete_collection("stylecart_kb")
except:
    pass

collection = client.create_collection("stylecart_kb")

documents = [
    {"id": "doc_001", "topic": "Return Policy", "text": "StyleCart accepts product returns within 7 days of delivery. Items must be unused, unwashed, and in their original condition with all tags attached. Items that have been worn, washed, damaged, or altered are not eligible. To initiate a return, go to My Orders and click Request Return, or message WhatsApp at +91-98765-43210. Pickup is scheduled within 2 business days after approval. Refunds are processed within 5-7 business days after the item is received and inspected. Refunds go to the original payment method. COD order refunds require bank account details."},
    {"id": "doc_002", "topic": "Shipping and Delivery", "text": "StyleCart ships to all major cities across India. Orders are dispatched within 24 hours on business days. Standard delivery takes 3 to 5 business days. Express delivery costs Rs. 99 extra and delivers in 2 business days. Remote areas may take 7 to 10 business days. Free standard shipping on orders above Rs. 999. Orders below Rs. 999 have a flat shipping fee of Rs. 49. A tracking link is sent via SMS and email after dispatch. International shipping is not available."},
    {"id": "doc_003", "topic": "Payment Methods", "text": "StyleCart accepts UPI (Google Pay, PhonePe, Paytm), credit cards (Visa, Mastercard, Rupay), debit cards, and net banking from all major Indian banks. EMI is available on credit card purchases above Rs. 3,000 for 3, 6, and 12 months. Cash on Delivery is available for orders up to Rs. 5,000 at serviceable pin codes. Prepaid orders receive a 5% instant discount. COD orders have an extra Rs. 50 handling fee. Payments are processed through a secure PCI-compliant gateway."},
    {"id": "doc_004", "topic": "Order Tracking", "text": "Track orders two ways: a tracking link is sent via SMS and email after dispatch, or log in to My Orders and click the order to see live status. Statuses include: Order Placed, Payment Confirmed, Processing, Dispatched, Out for Delivery, and Delivered. If the order shows Dispatched but no movement for over 3 days, contact support with the Order ID."},
    {"id": "doc_005", "topic": "Exchange Process", "text": "Exchanges are allowed within 7 days of delivery, subject to stock availability. Go to My Orders and click Request Exchange. Specify the reason and preferred size or colour. Customers pay return shipping cost. StyleCart ships the replacement free. Exchanges are not available for sale or discounted items. If the desired size or colour is out of stock, a full refund is offered instead."},
    {"id": "doc_006", "topic": "Order Cancellation Policy", "text": "Orders can be cancelled within 2 hours of placing, if not yet dispatched. Go to My Orders and click Cancel Order. If the order is in Processing or Dispatched status, cancellation is not possible — wait for delivery and initiate a return. Prepaid orders cancelled within 2 hours are refunded in 5-7 business days. COD cancelled orders need no refund. Repeated cancellations may suspend COD privileges."},
    {"id": "doc_007", "topic": "Size Guide", "text": "StyleCart offers sizes XS, S, M, L, XL, XXL, and 3XL for tops, kurtas, and dresses. Bottoms range from waist 26 to 40 inches. A size chart is on every product page. Chest measurements for tops: XS=32, S=34, M=36, L=38, XL=40, XXL=42, 3XL=44 inches. When between sizes, size up for comfort. Sizes may vary between product categories."},
    {"id": "doc_008", "topic": "Loyalty Points Program", "text": "StyleCart's loyalty program is called StyleCoins. Earn 1 StyleCoin per Rs. 10 on prepaid orders. COD orders earn StyleCoins only after successful delivery. 100 StyleCoins = Rs. 10 discount. Maximum 500 StyleCoins (Rs. 50) redeemable per order. StyleCoins expire 12 months after earning. Check balance in My Rewards. StyleCoins are reversed on returned or cancelled orders."},
    {"id": "doc_009", "topic": "COD and Prepaid Offers", "text": "COD is available for orders up to Rs. 5,000 at serviceable pin codes, with Rs. 50 handling fee. Prepaid orders via UPI, credit card, debit card, or net banking get a 5% instant discount. Prepaid orders are dispatched faster. First-time customers get 10% off on the first prepaid order with code WELCOME10 (one-time use). EMI is only on prepaid credit card payments above Rs. 3,000."},
    {"id": "doc_010", "topic": "Customer Support and Escalation", "text": "StyleCart support is available Monday to Saturday, 9 AM to 7 PM IST. Contact via WhatsApp at +91-98765-43210, email at support@stylecart.in, or live chat on the website or app. Response within 4 hours during business hours. Unresolved issues after 48 hours can be escalated to grievance@stylecart.in, responded to within 24 hours. Have your Order ID ready for delivery issues. No phone call support available."},
]

texts = [d["text"] for d in documents]
embeddings = embedder.encode(texts).tolist()
collection.add(
    documents=texts,
    embeddings=embeddings,
    ids=[d["id"] for d in documents],
    metadatas=[{"topic": d["topic"]} for d in documents]
)
print(f"ChromaDB ready: {collection.count()} documents.")


# ============================================================
# NODE 1: memory_node
# Stores message history and extracts customer name.
# ============================================================
def memory_node(state: CapstoneState) -> dict:
    messages = state.get("messages", [])
    question = state["question"]

    # Add the new user question to history
    messages = messages + [{"role": "user", "content": question}]

    # Sliding window: keep only last SLIDING_WINDOW messages
    messages = messages[-SLIDING_WINDOW:]

    # Extract customer name if introduced
    customer_name = state.get("customer_name", "")
    q_lower = question.lower()
    if "my name is" in q_lower:
        parts = q_lower.split("my name is")
        if len(parts) > 1:
            name_part = parts[1].strip().split()[0]
            customer_name = name_part.capitalize()

    return {
        "messages": messages,
        "customer_name": customer_name,
        "eval_retries": 0   # Reset retry counter for each new question
    }


# ============================================================
# NODE 2: router_node
# Uses LLM to decide: retrieve / tool / memory_only
# ============================================================
def router_node(state: CapstoneState) -> dict:
    question = state["question"]
    messages = state.get("messages", [])
    history_text = "\n".join(
        [f"{m['role'].upper()}: {m['content']}" for m in messages[-4:]]
    )

    prompt = f"""
You are a router for StyleCart customer support.

Reply with EXACTLY ONE WORD: retrieve, tool, or memory_only.

Rules:
- retrieve → ANY question about:
  returns, shipping, delivery, payments, COD, tracking, sizes, exchanges, loyalty points, cancellation, policies
- tool → ONLY for current date or time questions
- memory_only → ONLY for greetings, thanks, or when the answer is already clearly in the conversation

STRICT RULE:
If the question is about the store or any information → ALWAYS choose retrieve

Examples:
"What is return policy?" → retrieve
"How long does shipping take?" → retrieve
"Do you accept COD?" → retrieve
"Hi" → memory_only
"What is today's date?" → tool

Conversation history:
{history_text}

Customer question: {question}

Route:
""

Reply with ONE WORD only (retrieve, tool, or memory_only):"""

    response = llm.invoke(prompt)
    route = response.content.strip().lower()

    # Safety: default to retrieve if unexpected response
    if route not in ["retrieve", "tool", "memory_only"]:
        route = "retrieve"

    print(f"[router_node] Route decided: {route}")
    return {"route": route}


# ============================================================
# NODE 3: retrieval_node
# Searches ChromaDB and returns top 3 relevant chunks.
# ============================================================
def retrieval_node(state: CapstoneState) -> dict:
    question = state["question"]

    query_embedding = embedder.encode([question]).tolist()
    results = collection.query(
        query_embeddings=query_embedding,
        n_results=3
    )

    # Build context string with topic labels
    chunks = results["documents"][0]
    metadatas = results["metadatas"][0]

    context_parts = []
    sources = []
    for chunk, meta in zip(chunks, metadatas):
        topic = meta["topic"]
        context_parts.append(f"[{topic}]\n{chunk}")
        sources.append(topic)

    retrieved = "\n\n".join(context_parts)
    print(f"[retrieval_node] Retrieved topics: {sources}")
    return {"retrieved": retrieved, "sources": sources}


# ============================================================
# NODE 4: skip_retrieval_node
# Returns empty context for memory_only queries.
# Must explicitly set retrieved='' to avoid state leak.
# ============================================================
def skip_retrieval_node(state: CapstoneState) -> dict:
    print("[skip_retrieval_node] Skipping retrieval.")
    return {"retrieved": "", "sources": []}


# ============================================================
# NODE 5: tool_node
# Returns current date/time. Never raises exceptions.
# ============================================================
def tool_node(state: CapstoneState) -> dict:
    try:
        now = datetime.now()
        tool_result = (
            f"Today's date is {now.strftime('%A, %d %B %Y')}. "
            f"Current time is {now.strftime('%I:%M %p')} IST."
        )
        print(f"[tool_node] {tool_result}")
    except Exception as e:
        # Tools MUST never raise — return error string instead
        tool_result = f"Could not fetch the current date. Error: {str(e)}"

    return {"tool_result": tool_result, "retrieved": "", "sources": []}


# ============================================================
# NODE 6: answer_node
# Generates the final answer from context only.
# ============================================================
def answer_node(state: CapstoneState) -> dict:
    question = state["question"]
    retrieved = state.get("retrieved", "")
    tool_result = state.get("tool_result", "")
    messages = state.get("messages", [])
    customer_name = state.get("customer_name", "")
    eval_retries = state.get("eval_retries", 0)

    # Build conversation history string
    history_text = ""
    if len(messages) > 1:
        history_text = "\n".join(
            [f"{m['role'].upper()}: {m['content']}" for m in messages[:-1]]
        )

    # Address customer by name if known
    name_instruction = f"Address the customer as {customer_name}." if customer_name else ""

    # Escalation instruction on retry
    retry_instruction = ""
    if eval_retries >= 1:
        retry_instruction = "Your previous answer may have included information not in the context. Be more careful — use ONLY the information explicitly provided below."

    system_prompt = f"""You are a helpful and friendly customer support assistant for StyleCart, an Indian fashion and lifestyle e-commerce store.

STRICT RULE: Answer ONLY using information from the CONTEXT sections below. Do NOT use any general knowledge or make up information. If the answer is not in the context, say clearly: "I don't have that specific information. Please contact our support team on WhatsApp at +91-98765-43210 or email support@stylecart.in."

{name_instruction}
{retry_instruction}"""

    # Build context block
    context_block = ""
    if retrieved:
        context_block += f"\n\nKNOWLEDGE BASE CONTEXT:\n{retrieved}"
    if tool_result:
        context_block += f"\n\nTOOL RESULT (use this for date/time questions):\n{tool_result}"
    if not retrieved and not tool_result:
        context_block = "\n\nCONTEXT: Use only the conversation history to answer."

    user_message = f"""Conversation history:
{history_text}

{context_block}

Customer question: {question}

Your answer:"""

    response = llm.invoke(f"{system_prompt}\n\n{user_message}")
    answer = response.content.strip()

    print(f"[answer_node] Answer generated (retry {eval_retries}).")
    return {"answer": answer}


# ============================================================
# NODE 7: eval_node
# Scores faithfulness 0.0–1.0. Retries if below threshold.
# ============================================================
def eval_node(state: CapstoneState) -> dict:
    answer = state.get("answer", "")
    retrieved = state.get("retrieved", "")
    eval_retries = state.get("eval_retries", 0)

    # Skip evaluation if no retrieved context (tool or memory_only route)
    if not retrieved:
        print("[eval_node] No retrieved context — skipping faithfulness check.")
        return {"faithfulness": 1.0, "eval_retries": eval_retries}

    prompt = f"""You are an evaluator. Score whether the given ANSWER is faithful to the CONTEXT.
Faithful means: every claim in the answer is supported by the context. No made-up information.

Score from 0.0 to 1.0:
- 1.0 = completely faithful, every fact comes from the context
- 0.7 = mostly faithful, minor additions
- 0.5 = partially faithful, some unsupported claims
- 0.0 = completely unfaithful, answer ignores or contradicts context

CONTEXT:
{retrieved}

ANSWER:
{answer}

Reply with ONLY a number between 0.0 and 1.0. No explanation."""

    try:
        response = llm.invoke(prompt)
        score_text = response.content.strip()
        faithfulness = float(score_text)
        faithfulness = max(0.0, min(1.0, faithfulness))  # clamp to [0,1]
    except:
        faithfulness = 0.5   # default if parsing fails

    eval_retries = eval_retries + 1
    print(f"[eval_node] Faithfulness score: {faithfulness:.2f} | Retries: {eval_retries}")
    return {"faithfulness": faithfulness, "eval_retries": eval_retries}


# ============================================================
# NODE 8: save_node
# Appends the final answer to conversation history.
# ============================================================
def save_node(state: CapstoneState) -> dict:
    messages = state.get("messages", [])
    answer = state.get("answer", "")

    messages = messages + [{"role": "assistant", "content": answer}]
    print("[save_node] Answer saved to history.")
    return {"messages": messages}


# ============================================================
# INDIVIDUAL NODE TESTS (run each node in isolation)
# ============================================================
if __name__ == "__main__":
    print("\n" + "="*50)
    print("TESTING EACH NODE IN ISOLATION")
    print("="*50)

    # Mock state
    mock_state: CapstoneState = {
        "question": "What is your return policy?",
        "messages": [],
        "route": "",
        "retrieved": "",
        "sources": [],
        "tool_result": "",
        "answer": "",
        "faithfulness": 0.0,
        "eval_retries": 0,
        "customer_name": ""
    }

    print("\n--- Test: memory_node ---")
    result = memory_node(mock_state)
    print(f"Messages count: {len(result['messages'])}")

    print("\n--- Test: router_node ---")
    mock_state.update(result)
    result2 = router_node(mock_state)
    print(f"Route: {result2['route']}")

    print("\n--- Test: retrieval_node ---")
    mock_state.update(result2)
    result3 = retrieval_node(mock_state)
    print(f"Sources: {result3['sources']}")

    print("\n--- Test: tool_node ---")
    tool_state = {**mock_state, "question": "What is today's date?"}
    result_tool = tool_node(tool_state)
    print(f"Tool result: {result_tool['tool_result']}")

    print("\n--- Test: answer_node ---")
    mock_state.update(result3)
    result4 = answer_node(mock_state)
    print(f"Answer preview: {result4['answer'][:100]}...")

    print("\n--- Test: eval_node ---")
    mock_state.update(result4)
    result5 = eval_node(mock_state)
    print(f"Faithfulness: {result5['faithfulness']}")

    print("\n--- Test: save_node ---")
    mock_state.update(result5)
    result6 = save_node(mock_state)
    print(f"Total messages after save: {len(result6['messages'])}")

    print("\n✅ Part 3 complete. All nodes tested.")